name: SimpleTest
main: net.shibacraft.simpletest.SimpleTest
version: '${v}'
author: SKJOLBERG
api-version: 1.13
softdepend:
  - SimplePlugin
permissions:
  st.admin:
    description: Allows all admin permissions
    default: op
    children:
      - sdi.use
  st.use:
    default: false
    description: Allows you to use the command to drop items to the inventory